/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt';
import { Route as OrderConfirmationRouteImport } from './routes/order-confirmation';
import { Route as AboutRouteImport } from './routes/about';
import { Route as CheckoutRouteRouteImport } from './routes/checkout/route';
import { Route as ShopRouteRouteImport } from './routes/_shop/route';
import { Route as ShopIndexRouteImport } from './routes/_shop/index';
import { Route as CheckoutCancelRouteImport } from './routes/checkout/cancel';
import { Route as ApiProductsIndexRouteImport } from './routes/api/products/index';
import { Route as ShopProductsIndexRouteImport } from './routes/_shop/products/index';
import { Route as ApiAssetsAssetRouteImport } from './routes/api/assets/$asset';
import { Route as ShopProductsSlugRouteImport } from './routes/_shop/products/$slug';
import { Route as ApiCheckoutEventsIndexRouteImport } from './routes/api/checkout/events/index';

const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any);
const OrderConfirmationRoute = OrderConfirmationRouteImport.update({
  id: '/order-confirmation',
  path: '/order-confirmation',
  getParentRoute: () => rootRouteImport,
} as any);
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any);
const CheckoutRouteRoute = CheckoutRouteRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any);
const ShopRouteRoute = ShopRouteRouteImport.update({
  id: '/_shop',
  getParentRoute: () => rootRouteImport,
} as any);
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRouteRoute,
} as any);
const CheckoutCancelRoute = CheckoutCancelRouteImport.update({
  id: '/cancel',
  path: '/cancel',
  getParentRoute: () => CheckoutRouteRoute,
} as any);
const ApiProductsIndexRoute = ApiProductsIndexRouteImport.update({
  id: '/api/products/',
  path: '/api/products/',
  getParentRoute: () => rootRouteImport,
} as any);
const ShopProductsIndexRoute = ShopProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => ShopRouteRoute,
} as any);
const ApiAssetsAssetRoute = ApiAssetsAssetRouteImport.update({
  id: '/api/assets/$asset',
  path: '/api/assets/$asset',
  getParentRoute: () => rootRouteImport,
} as any);
const ShopProductsSlugRoute = ShopProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => ShopRouteRoute,
} as any);
const ApiCheckoutEventsIndexRoute = ApiCheckoutEventsIndexRouteImport.update({
  id: '/api/checkout/events/',
  path: '/api/checkout/events/',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof ShopIndexRoute;
  '/checkout': typeof CheckoutRouteRouteWithChildren;
  '/about': typeof AboutRoute;
  '/order-confirmation': typeof OrderConfirmationRoute;
  '/robots.txt': typeof RobotsDottxtRoute;
  '/checkout/cancel': typeof CheckoutCancelRoute;
  '/products/$slug': typeof ShopProductsSlugRoute;
  '/api/assets/$asset': typeof ApiAssetsAssetRoute;
  '/products/': typeof ShopProductsIndexRoute;
  '/api/products/': typeof ApiProductsIndexRoute;
  '/api/checkout/events/': typeof ApiCheckoutEventsIndexRoute;
}
export interface FileRoutesByTo {
  '/checkout': typeof CheckoutRouteRouteWithChildren;
  '/about': typeof AboutRoute;
  '/order-confirmation': typeof OrderConfirmationRoute;
  '/robots.txt': typeof RobotsDottxtRoute;
  '/checkout/cancel': typeof CheckoutCancelRoute;
  '/': typeof ShopIndexRoute;
  '/products/$slug': typeof ShopProductsSlugRoute;
  '/api/assets/$asset': typeof ApiAssetsAssetRoute;
  '/products': typeof ShopProductsIndexRoute;
  '/api/products': typeof ApiProductsIndexRoute;
  '/api/checkout/events': typeof ApiCheckoutEventsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/_shop': typeof ShopRouteRouteWithChildren;
  '/checkout': typeof CheckoutRouteRouteWithChildren;
  '/about': typeof AboutRoute;
  '/order-confirmation': typeof OrderConfirmationRoute;
  '/robots.txt': typeof RobotsDottxtRoute;
  '/checkout/cancel': typeof CheckoutCancelRoute;
  '/_shop/': typeof ShopIndexRoute;
  '/_shop/products/$slug': typeof ShopProductsSlugRoute;
  '/api/assets/$asset': typeof ApiAssetsAssetRoute;
  '/_shop/products/': typeof ShopProductsIndexRoute;
  '/api/products/': typeof ApiProductsIndexRoute;
  '/api/checkout/events/': typeof ApiCheckoutEventsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/checkout'
    | '/about'
    | '/order-confirmation'
    | '/robots.txt'
    | '/checkout/cancel'
    | '/products/$slug'
    | '/api/assets/$asset'
    | '/products/'
    | '/api/products/'
    | '/api/checkout/events/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/checkout'
    | '/about'
    | '/order-confirmation'
    | '/robots.txt'
    | '/checkout/cancel'
    | '/'
    | '/products/$slug'
    | '/api/assets/$asset'
    | '/products'
    | '/api/products'
    | '/api/checkout/events';
  id:
    | '__root__'
    | '/_shop'
    | '/checkout'
    | '/about'
    | '/order-confirmation'
    | '/robots.txt'
    | '/checkout/cancel'
    | '/_shop/'
    | '/_shop/products/$slug'
    | '/api/assets/$asset'
    | '/_shop/products/'
    | '/api/products/'
    | '/api/checkout/events/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  ShopRouteRoute: typeof ShopRouteRouteWithChildren;
  CheckoutRouteRoute: typeof CheckoutRouteRouteWithChildren;
  AboutRoute: typeof AboutRoute;
  OrderConfirmationRoute: typeof OrderConfirmationRoute;
  RobotsDottxtRoute: typeof RobotsDottxtRoute;
  ApiAssetsAssetRoute: typeof ApiAssetsAssetRoute;
  ApiProductsIndexRoute: typeof ApiProductsIndexRoute;
  ApiCheckoutEventsIndexRoute: typeof ApiCheckoutEventsIndexRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/robots.txt': {
      id: '/robots.txt';
      path: '/robots.txt';
      fullPath: '/robots.txt';
      preLoaderRoute: typeof RobotsDottxtRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/order-confirmation': {
      id: '/order-confirmation';
      path: '/order-confirmation';
      fullPath: '/order-confirmation';
      preLoaderRoute: typeof OrderConfirmationRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/about': {
      id: '/about';
      path: '/about';
      fullPath: '/about';
      preLoaderRoute: typeof AboutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/checkout': {
      id: '/checkout';
      path: '/checkout';
      fullPath: '/checkout';
      preLoaderRoute: typeof CheckoutRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_shop': {
      id: '/_shop';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof ShopRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_shop/': {
      id: '/_shop/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof ShopIndexRouteImport;
      parentRoute: typeof ShopRouteRoute;
    };
    '/checkout/cancel': {
      id: '/checkout/cancel';
      path: '/cancel';
      fullPath: '/checkout/cancel';
      preLoaderRoute: typeof CheckoutCancelRouteImport;
      parentRoute: typeof CheckoutRouteRoute;
    };
    '/api/products/': {
      id: '/api/products/';
      path: '/api/products';
      fullPath: '/api/products/';
      preLoaderRoute: typeof ApiProductsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_shop/products/': {
      id: '/_shop/products/';
      path: '/products';
      fullPath: '/products/';
      preLoaderRoute: typeof ShopProductsIndexRouteImport;
      parentRoute: typeof ShopRouteRoute;
    };
    '/api/assets/$asset': {
      id: '/api/assets/$asset';
      path: '/api/assets/$asset';
      fullPath: '/api/assets/$asset';
      preLoaderRoute: typeof ApiAssetsAssetRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_shop/products/$slug': {
      id: '/_shop/products/$slug';
      path: '/products/$slug';
      fullPath: '/products/$slug';
      preLoaderRoute: typeof ShopProductsSlugRouteImport;
      parentRoute: typeof ShopRouteRoute;
    };
    '/api/checkout/events/': {
      id: '/api/checkout/events/';
      path: '/api/checkout/events';
      fullPath: '/api/checkout/events/';
      preLoaderRoute: typeof ApiCheckoutEventsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

interface ShopRouteRouteChildren {
  ShopIndexRoute: typeof ShopIndexRoute;
  ShopProductsSlugRoute: typeof ShopProductsSlugRoute;
  ShopProductsIndexRoute: typeof ShopProductsIndexRoute;
}

const ShopRouteRouteChildren: ShopRouteRouteChildren = {
  ShopIndexRoute: ShopIndexRoute,
  ShopProductsSlugRoute: ShopProductsSlugRoute,
  ShopProductsIndexRoute: ShopProductsIndexRoute,
};

const ShopRouteRouteWithChildren = ShopRouteRoute._addFileChildren(
  ShopRouteRouteChildren
);

interface CheckoutRouteRouteChildren {
  CheckoutCancelRoute: typeof CheckoutCancelRoute;
}

const CheckoutRouteRouteChildren: CheckoutRouteRouteChildren = {
  CheckoutCancelRoute: CheckoutCancelRoute,
};

const CheckoutRouteRouteWithChildren = CheckoutRouteRoute._addFileChildren(
  CheckoutRouteRouteChildren
);

const rootRouteChildren: RootRouteChildren = {
  ShopRouteRoute: ShopRouteRouteWithChildren,
  CheckoutRouteRoute: CheckoutRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  OrderConfirmationRoute: OrderConfirmationRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ApiAssetsAssetRoute: ApiAssetsAssetRoute,
  ApiProductsIndexRoute: ApiProductsIndexRoute,
  ApiCheckoutEventsIndexRoute: ApiCheckoutEventsIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from './router.tsx';
import type { createStart } from '@tanstack/react-start';
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
